### ISSUE TITLE
Second attempt to see the same video results in "There was an error processing your request!" error

### ISSUE THREAD

**Issue by onnimonni** [pablouser1/ProxiTok#217]
Before submitting an issue, please make sure you are using the latest version of ProxiTok.

**Describe the bug**
When I try to see the same video twice in short amount of time the proxy works on the 1st attempt but fails on 2nd.

**To Reproduce**
1. Go to https://proxitok.pabloferreiro.es/
2. Input a video like https://www.tiktok.com/@diariesofacodegirl/video/7307747910765038854
3. See the video succesfully
4. Refresh the page
5. See the following error message:
<img width="993" alt="Screenshot 2024-05-01 at 10 49 50" src="https://github.com/pablouser1/ProxiTok/assets/5691777/78323dc9-5cf7-4e83-bc46-5f4e3a738ba1">

**Expected behavior**
Being able to see the same video again

**Comment by pablouser1** [comment]
Should be fixed with #224

**Comment by Teko012** [comment]
@pablouser1 It still happens on your instance, which I think runs that version already.

**Comment by pablouser1** [comment]
Can confirm it... It only happens with videos, the other items use cache properly. I'm investigating it.

**Comment by pablouser1** [comment]
Hi! pablouser1/TikScraperPHP@c8540e5dfaf8ec807cafd4ab45982163f2a47c74 should fix the issue. Now I can refresh the page without issues

@Teko012 please confirm it also works on your end.

**Comment by Teko012** [comment]
@Teko012 yep 👍
