### ISSUE TITLE
Changes on tiktok side breaks user posts retreival (new signature?)

### ISSUE THREAD

**Issue by vdemay** [pablouser1/ProxiTok#94]
Get user videos does not work anymore probably due to a change on tiktok tt-parameter generation

How to reproduce:
 1/ go to https://proxitok.pabloferreiro.es/@willsmith -> working because content has been captured while getting user info
 2/ go to the bottom of the page and click Next -> Error
 
 Actually I suppose the end point `user/item_list` needs a new signing method or new parameters to work properly.

**Comment by vdemay** [comment]
Same ticket open here : https://github.com/carcabot/tiktok-signature/issues/168

**Comment by vdemay** [comment]
Hello,

Thanks for the update. But unfortunately, it still does not work. 

I suppose the first page for willsmith account is now in cache so it display well. But if you try with another account it does not work.

Tiktok puts probably a short expiration time on one of the parameter of the requests leading the fix of @carcabot to work only for a short period of time - see https://github.com/carcabot/tiktok-signature/issues/168

This can also be useful - same issue -  https://github.com/davidteather/TikTok-Api/issues/974

Thanks for your work on this

**Comment by pablouser1** [comment]
Thanks for the heads up, I'll check it out and implement it when I have time.

**Comment by pablouser1** [comment]
Looks like changing the User Agent of the scraper to a smartphone (`Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36` is currently in use) helps.

Why? ¯\_(ツ)_/¯ I really don't know. I don't know if this will work with many requets, we'll see.

**Comment by NoPlagiarism** [comment]
I guess, it's time to create `/health` endpoint? Or idk.

**Comment by LukeLR** [comment]
In #126 I exposed the user_agent parameter of the TikScraper API as an environment variable. However, setting the value recommended by @pablouser1 there does not fix the 503 Error when clicking next on a user's page. Am I doing something wrong, or does this approach no longer work?

**Comment by desbest** [comment]
Is there an update on this?

**Comment by xbdmHQ** [comment]
> Is there an update on this?
The issue is fixed, They probably are using the same port by mistake. Try mines, Which i requested to be on the public instance list: https://cringe.xbdm.fun/ (Everything works too)

**Comment by SuperSonicHub1** [comment]
This is still a problem for me, both with ProxiTok and using TikScraper directly in a project for work. It seems errors with requesting stuff with a non-zero cursor can be overcome by reloading the page multiple times.

**Comment by SuperSonicHub1** [comment]
I've done a bit more digging and have found that the URLs TikScraper and TikTok's web frontend generate have some differences. When requesting extra videos for [this creator](https://www.tiktok.com/@endomarf):
TikScraper:
```json
{
	"host": "tiktok.com",
	"pathname": "/api/post/item_list",
	"searchParams": [
		[
			"X-Bogus",
			"DFSzswVL-XGANHVWS0OnS2XyYJUm"
		],
		[
			"_signature",
			"_02B4Z6wo00001Pf0DlwAAIDB1FUg8jgaqOz39ArAAF6Z72"
		],
		[
			"aid",
			"1988"
		],
		[
			"app_language",
			"en"
		],
		[
			"app_name",
			"tiktok_web"
		],
		[
			"battery_info",
			"1"
		],
		[
			"browser_language",
			"en-US"
		],
		[
			"browser_name",
			"Mozilla"
		],
		[
			"browser_online",
			"true"
		],
		[
			"browser_platform",
			"Win32"
		],
		[
			"browser_version",
			"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35"
		],
		[
			"channel",
			"tiktok_web"
		],
		[
			"cookie_enabled",
			"true"
		],
		[
			"device_id",
			"7002566096994190854"
		],
		[
			"device_platform",
			"web_pc"
		],
		[
			"focus_state",
			"false"
		],
		[
			"from_page",
			"user"
		],
		[
			"history_len",
			"3"
		],
		[
			"is_fullscreen",
			"false"
		],
		[
			"is_page_visible",
			"true"
		],
		[
			"msToken",
			"7UfjxOYL5mVC8QFOKQRhmLR3pCjoxewuwxtfFIcPweqC05Q6C_qjW-5Ba6_fE5-fkZc0wkLSWaaesA4CZ0LAqRrXSL8b88jGvEjbZPwLIPnHeyQq6VifzyKf5oGCQNw_W4Xq12Q-8KCuyiKGLOw="
		],
		[
			"os",
			"windows"
		],
		[
			"priority_region",
			"RO"
		],
		[
			"referer",
			"https://exportcomments.com/"
		],
		[
			"region",
			"RO"
		],
		[
			"root_referer",
			"https://exportcomments.com/"
		],
		[
			"screen_height",
			"1440"
		],
		[
			"screen_width",
			"2560"
		],
		[
			"tz_name",
			"Europe/Bucharest"
		],
		[
			"verifyFp",
			"verify_lacphy8d_z2ux9idt_xdmu_4gKb_9nng_NNTTTvsFS8ao"
		],
		[
			"webcast_language",
			"en"
		]
	]
}
```
TikTok:
```json:
{
	"host": "tiktok.com",
	"pathname": "/api/post/item_list",
	"searchParams": [
		[
			"X-Bogus",
			"DFSz0IjLJKxANnmqtjxMH4uXu8BJ"
		],
		[
			"_signature",
			"_02B4Z6wo00001g7j9rAAAIDA1MaXSEryDO4O4eIAAOcP24"
		],
		[
			"aid",
			"1988"
		],
		[
			"app_language",
			"en"
		],
		[
			"app_name",
			"tiktok_web"
		],
		[
			"browser_language",
			"en-US"
		],
		[
			"browser_name",
			"Mozilla"
		],
		[
			"browser_online",
			"true"
		],
		[
			"browser_platform",
			"Linux x86_64"
		],
		[
			"browser_version",
			"5.0 (X11; Ubuntu)"
		],
		[
			"channel",
			"tiktok_web"
		],
		[
			"cookie_enabled",
			"true"
		],
		[
			"count",
			"35"
		],
		[
			"cursor",
			"1641405430000"
		],
		[
			"device_id",
			"7257555475197445633"
		],
		[
			"device_platform",
			"web_pc"
		],
		[
			"focus_state",
			"false"
		],
		[
			"from_page",
			"user"
		],
		[
			"history_len",
			"4"
		],
		[
			"is_fullscreen",
			"false"
		],
		[
			"is_page_visible",
			"true"
		],
		[
			"language",
			"en"
		],
		[
			"msToken",
			"ehJMYCuBRkWmi-MCtkJb3MB2EJtcJA4ugrTYC0kCymTfVndUEAqX0FTgafOj2lMOz7dxXUiOvd7YZ1gYFnu8qy57aAfzPOrAKEmXrj3fN4Ia7Ohtl6ZQ3aZTc_Vf3rqvmOWWq3OWBCfPbk8x"
		],
		[
			"os",
			"linux"
		],
		[
			"priority_region",
			""
		],
		[
			"referer",
			""
		],
		[
			"region",
			"US"
		],
		[
			"screen_height",
			"1620"
		],
		[
			"screen_width",
			"2880"
		],
		[
			"secUid",
			"MS4wLjABAAAAY54yPKagfVHFm_AHR5n9oDiKj3Xl_GvAotRUTcJCGpjBgi35dDbWdKu5sfy4IcMX"
		],
		[
			"tz_name",
			"America/New_York"
		],
		[
			"verifyFp",
			"verify_lkbbmp1l_3eDlJTmB_CexW_4cZN_8G2a_kukLFsSP6Orv"
		],
		[
			"webcast_language",
			"en"
		]
	]
}
```
Parameters only in TikTok of note:
- count
- cursor (had to do a triple check to see that this wasn't being included in our requests; weird)

**Comment by Sainttttttttttt** [comment]
I cant use it

**Comment by pablouser1** [comment]
Should be fixed with #224
